---
- name: ensure postfix is installed
  apt: name=postfix state=present
  when: ansible_distribution == "Debian"

- name: ensure postfix is running
  service: name=postfix enabled=yes state=started

- name: update main.cf
  template:
    src: template/main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  register: postfix

- name: update generic
  template:
    src: template/generic.j2
    dest: /etc/postfix/generic
    owner: root
    group: root
    mode: 0644
  register: postfix_generic

- name: update generic.db
  shell: |
    cd /etc/postfix
    postmap generic
  when: postfix_generic.changed

- name: update sasl_passwd
  template:
    src: template/sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: 0600
  register: postfix_sasl_passwd

- name: update sasl_passwd.db
  shell: |
    cd /etc/postfix
    postmap sasl_passwd
  when: postfix_sasl_passwd.changed

- name: restart postfix
  service: name=postfix state=restarted
  when: postfix.changed or postfix_sasl_passwd.changed

